# Generated by Django 3.2.3 on 2021-05-31 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AugmentedData',
            fields=[
                ('pobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.pobject')),
            ],
            bases=('main.pobject',),
        ),
        migrations.CreateModel(
            name='DictObject',
            fields=[
                ('pobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.pobject')),
            ],
            bases=('main.pobject',),
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('pobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.pobject')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, choices=[('String', 'String'), ('Datetime', 'Datetime'), ('File', 'File'), ('Text', 'Text')], max_length=255)),
                ('value', models.TextField(blank=True)),
            ],
            bases=('main.pobject',),
        ),
        migrations.CreateModel(
            name='PResource',
            fields=[
                ('pobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.pobject')),
            ],
            bases=('main.pobject',),
        ),
        migrations.CreateModel(
            name='DictElement',
            fields=[
                ('dictobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.dictobject')),
                ('value', models.CharField(blank=True, max_length=255)),
            ],
            bases=('main.dictobject',),
        ),
        migrations.CreateModel(
            name='DictPackage',
            fields=[
                ('dictobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.dictobject')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('elements', models.ManyToManyField(blank=True, related_name='package', to='main.DictObject')),
            ],
            bases=('main.dictobject',),
        ),
        migrations.CreateModel(
            name='PFile',
            fields=[
                ('presource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.presource')),
                ('file', models.FileField(blank=True, upload_to='upload')),
            ],
            bases=('main.presource',),
        ),
        migrations.CreateModel(
            name='PText',
            fields=[
                ('augmenteddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.augmenteddata')),
                ('text', models.TextField(blank=True)),
            ],
            bases=('main.augmenteddata',),
        ),
        migrations.CreateModel(
            name='PUri',
            fields=[
                ('presource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.presource')),
                ('uri', models.URLField(blank=True)),
            ],
            bases=('main.presource',),
        ),
        migrations.AddField(
            model_name='augmenteddata',
            name='associatedDatas',
            field=models.ManyToManyField(blank=True, related_name='augmentedData', to='main.PResource'),
        ),
        migrations.AddField(
            model_name='augmenteddata',
            name='metaDatas',
            field=models.ManyToManyField(blank=True, related_name='augmentedData', to='main.MetaData'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('dictpackage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.dictpackage')),
                ('type', models.CharField(blank=True, choices=[('ENTITY', 'ENTITY'), ('QUALITY', 'QUALITY'), ('VERB', 'VERB'), ('MARKER', 'MARKER')], max_length=255)),
            ],
            bases=('main.dictpackage',),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('dictpackage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.dictpackage')),
            ],
            bases=('main.dictpackage',),
        ),
        migrations.CreateModel(
            name='Dictionnary',
            fields=[
                ('dictpackage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.dictpackage')),
                ('type', models.CharField(blank=True, choices=[('FictionDict', 'FictionDict'), ('CollectionDict', 'CollectionDict'), ('CategoryDict', 'CategoryDict'), ('SyntaxicDict', 'SyntaxicDict')], max_length=255)),
            ],
            bases=('main.dictpackage',),
        ),
        migrations.CreateModel(
            name='Fiction',
            fields=[
                ('dictpackage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.dictpackage')),
            ],
            bases=('main.dictpackage',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('augmenteddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.augmenteddata')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=255)),
                ('texts', models.ManyToManyField(blank=True, related_name='project', to='main.PText')),
                ('dictionnaries', models.ManyToManyField(blank=True, related_name='project', to='main.Dictionnary')),
            ],
            bases=('main.augmenteddata',),
        ),
        migrations.CreateModel(
            name='LexicalDictionnary',
            fields=[
                ('dictionnary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.dictionnary')),
                ('language', models.CharField(blank=True, max_length=255)),
            ],
            bases=('main.dictionnary',),
        ),
        migrations.CreateModel(
            name='SemanticDictionnary',
            fields=[
                ('dictionnary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.dictionnary')),
            ],
            bases=('main.dictionnary',),
        ),
        migrations.CreateModel(
            name='Prospero',
            fields=[
                ('pobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.pobject')),
                ('projects', models.ManyToManyField(blank=True, related_name='prospero', to='main.Project')),
                ('texts', models.ManyToManyField(blank=True, related_name='prospero', to='main.PText')),
                ('dictionnaries', models.ManyToManyField(blank=True, related_name='prospero', to='main.Dictionnary')),
            ],
            bases=('main.pobject',),
        ),
        migrations.CreateModel(
            name='CategoryDictionnary',
            fields=[
                ('semanticdictionnary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.semanticdictionnary')),
            ],
            bases=('main.semanticdictionnary',),
        ),
        migrations.CreateModel(
            name='CollectionDictionnary',
            fields=[
                ('semanticdictionnary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.semanticdictionnary')),
            ],
            bases=('main.semanticdictionnary',),
        ),
        migrations.CreateModel(
            name='FictionDictionnary',
            fields=[
                ('semanticdictionnary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.semanticdictionnary')),
            ],
            bases=('main.semanticdictionnary',),
        ),
    ]
